language: python

sudo: false

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

branches:
 only:
 - master
 - devel
  - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

cache:
- pip: true

git:
  depth: 3

before_install:
- travis_retry pip install --upgrade pip setuptools wheel pytest pytest-cov

install:
- pip install .

script:
- pytest -v -rsx --cov --cov-report=xml

after_success:
- codecov

notifications:
  slack: biosustain:8QjrEi8U59rrS3W8CtvOwc5T
