language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

git:
  depth: 2

cache:
  pip: true

branches:
  only:
    - master
    - devel
    - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"

env:
  global:
    - GITHUB_REPO=biosustain/driven

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel tox tox-travis

script:
  - tox -- --cov=driven --cov-report xml --cov-report term
  - bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
  - stage: deploy
    install: skip
    script:
    - echo "Deploying driven."
    deploy:
    - provider: pypi
      skip_cleanup: true
      distributions: sdist bdist_wheel
      user: midnighter
      password: $PYPI_PASSWORD
      on:
        tags: true
        repo: $GITHUB_REPO
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      body: "Please see https://github.com/${GITHUB_REPO}/blob/${TRAVIS_TAG}/CHANGELOG.rst for the full release notes."
      on:
        tags: true
        repo: $GITHUB_REPO

notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    on_pull_requests: false
